### ISSUE TITLE
Response

### ISSUE THREAD

**Issue by gotwilk890** [ga-wdi-boston/html-css-layout-positioning-study#1]
Different options for box-sizing are:

content-box : This is the default setting for box-sizing. The width and height properties you set do not include margin, padding, and border.

border-box : The width and heigh properties you set includes the padding and border in addition to the content.

initial : this sets the property to its default value. ( The value before box-sizing was done. )

inherit: takes on the property from its parent element.

Difference between relative and absolute positioning.

Relative positioning sets the position from its static position only if commanded to do so otherwise it takes on its normal static position.

Absolute Positioning sets the position to be relative to a non static positioned parent element. If no such parent exists then it relatively positions to the body element.

Gotchas!!

1) Not clearing a float
2) Box-model sizes overflow their bounds when a width and height is declared, then padding or borders are applied. 
3) Using absolute positioning on a div with no parent relative positioning.

**Comment by jrhorn424** [comment]
:+1: :star: Thanks!
