### ISSUE TITLE
Response - Kelvin

### ISSUE THREAD

**Issue by kelvinma** [ga-wdi-boston/html-css-layout-positioning-study#2]
1. When using box-sizing, the size of padding and border do not affect the overall width of the box itself. Contrast that with the traditional box model, which adds the size of the padding and border to the original width of the bordered/padded element.

2. Relative position elements can be moved away from their normal positions through location properties such as top, bottom, left and right. An absolute position element is given an specific location within a relatively positioned element.

3. "Gotchas"
    a. When floating an element, if the element that is being floated is bigger than its container, it will spill out beyond the container. That can be remedied with the clearfix hack.

    b. "Percent width" layouts can cause problems when viewed on a smaller screen or browser window. Responsive design through media queries can mitigate those problems.
 
    c. The box model can create problems can be problematic when working with elements of matching width, but dissimilar borders and padding. Using box-sizing instead can help create a consistent width throughout.

**Comment by jrhorn424** [comment]
:star: Thanks!
