### ISSUE TITLE
Response - Rachel

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/html-css-layout-positioning-study#3]
1. box-sizing can take content-box or border-box. Content-box is the default setting, and it will increase the width of the element as you add margins and/or borders. If set to border-box, the element will remain the same size on the page regardless of the padding or margins added.

2. Giving an element a relative position allows you to manipulate it relative to where it would normally be rendered on the page. You can 'push' it using left, right, top, and bottom. 
Absolutely positioned elements are positioned relative to their parent elements. You can use the same modifiers to move them around within their parent elements.

3. Common CSS mistakes include not adapting your website to multiple browsers, not adapting it to multiple screen sizes, and... I don't know what else. Not being able to do anything you want to do? :P

**Comment by jrhorn424** [comment]
:+1: Great, plain-English explanation of relative positioning!
