### ISSUE TITLE
Answers 

### ISSUE THREAD

**Issue by toymechqm** [ga-wdi-boston/html-css-layout-positioning-study#4]
What is the different options for box-sizing? Explain the differences between them.
We can make:
- box-sizing: border-box:
 "...on an element, the padding and border of that element no longer increase its width"
"This ensures that all elements are always sized in this more intuitive way."
It is reccommended to make sure you specify alternative browser prefixes because the box-sizing option is relatively new.
flex boxes
- content-box: this is the default style. "The width and height properties are measured including only the content, but not the padding, border or margin." -MDN
- border-box: "The width and height properties include the padding and border, but not the margin." -MDN

In your own words, explain the difference between relative and absolute positioning.
to understand absolute-positioning. it helps to understand fixed-positioning.
- fixed: fixed means that its position is fixed... so when you scroll the element will stay in the same position. We commonly see this for fixed header/navbars and footers.
- absolute: is similar to fixed. However it is 'tied' to its closest ancestor(The first simple selector within this selector represents the ancestor element -sitepoint.com). So the key here is that absolute is relative to its nearest ancestor and NOT the viewpoint like fixed is.
-relative: this is relatively similar to static positioning. if you set one element to relative, it really means that the element is static. The trick here is that there has to be 2 relative elements. if you define TRBL attributes to a specific element such as 10px, that relatively placed element will be 10px from where it normally would have been.

What are three "gotchas" when working with CSS layouts? 
"Gotchas" are common mistakes that are easy to make, even if you know better.
- forgetting cross compatibility with things like  you should use the -webkit- and -moz-
- "Mobile browsers have surprisingly shaky support for fixed"
- using absolute positioning
- problems with clearfix
- relative doesn't mean relative to another element, but rather, relative to itself.

**Comment by jrhorn424** [comment]
:+1: :star: Thanks!
