### ISSUE TITLE
Response

### ISSUE THREAD

**Issue by atsundwn** [ga-wdi-boston/html-css-layout-positioning-study#5]
1)  box-sizing has 2 options; content-box which is the default and border-box.  The content-box will not include padding and border values for width and height properties which means padding and width will add to the width and height of the element.  The border-box option will include the padding and border values for width and height values which makes calculating box sizes easier during positioning.

2)  Relative positioning will take the element in question and move relative to the top and left option from the left top corner.  Absolute positioning is positioning relative to the nearst positioned (not static, an element is said to be positioned if it's not static) parent; if there is no positioned parent, it will use the body as reference.

3)  Common mistakes are sizing that don't adapt to different screen sizes, what's called "responsive" design.  Other common mistakes include not accommodating other browsers that might view your file.  If other browsers don't support a certain type of property of if they are experimental, you need to make sure to include proper syntax to access the properties.

**Comment by jrhorn424** [comment]
:+1: Looks great! Thanks.
